mappings:
  - deprecatedAPI: "apiVersion: extensions/v1beta1[\\s]+kind: Deployment"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta1[\\s]+kind: Deployment"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2[\\s]+kind: Deployment"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta1[\\s]+kind: StatefulSet"
    newAPI: "apiVersion: apps/v1\nkind: StatefulSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2[\\s]+kind: StatefulSet"
    newAPI: "apiVersion: apps/v1\nkind: StatefulSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1[\\s]+kind: DaemonSet"
    newAPI: "apiVersion: apps/v1\nkind: DaemonSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2[\\s]+kind: DaemonSet"
    newAPI: "apiVersion: apps/v1\nkind: DaemonSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1[\\s]+kind: ReplicaSet"
    newAPI: "apiVersion: apps/v1\nkind: ReplicaSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta1[\\s]+kind: ReplicaSet"
    newAPI: "apiVersion: apps/v1\nkind: ReplicaSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2[\\s]+kind: ReplicaSet"
    newAPI: "apiVersion: apps/v1\nkind: ReplicaSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1[\\s]+kind: NetworkPolicy"
    newAPI: "apiVersion: networking.k8s.io/v1\nkind: NetworkPolicy"
    deprecatedInVersion: "v1.8"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1[\\s]+kind: PodSecurityPolicy"
    newAPI: "apiVersion: policy/v1beta1\nkind: PodSecurityPolicy"
    deprecatedInVersion: "v1.10"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apiextensions.k8s.io/v1beta1[\\s]+kind: CustomResourceDefinition"
    newAPI: "apiVersion: apiextensions.k8s.io/v1\nkind: CustomResourceDefinition"
    deprecatedInVersion: "v1.16"
    removedInVersion: "v1.19"
  - deprecatedAPI: "apiVersion: extensions/v1beta1[\\s]+kind: Ingress"
    newAPI: "apiVersion: networking.k8s.io/v1beta1\nkind: Ingress"
    deprecatedInVersion: "v1.14"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1[\\s]+kind: ClusterRole"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRole"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1[\\s]+kind: ClusterRoleList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1[\\s]+kind: ClusterRoleBinding"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBinding"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1[\\s]+kind: ClusterRoleBindingList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBindingList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1[\\s]+kind: Role"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: Role"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1[\\s]+kind: RoleList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1[\\s]+kind: RoleBinding"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1[\\s]+kind: RoleBindingList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBindingList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1[\\s]+kind: ClusterRole"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRole"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1[\\s]+kind: ClusterRoleList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1[\\s]+kind: ClusterRoleBinding"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBinding"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1[\\s]+kind: ClusterRoleBindingList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBindingList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1[\\s]+kind: Role"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: Role"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1[\\s]+kind: RoleList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1[\\s]+kind: RoleBinding"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1[\\s]+kind: RoleBindingList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBindingList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"